version: 0.2
phases:
  install:
    commands:
      # Install Python and pip (if not pre-installed in the build environment)
      - python3 -m pip install --upgrade pip
  pre_build:
    commands:
      # Install Python dependencies
      - pip3 install -r requirements-aws.txt
  build:
    commands:
      # Run your tests or build commands here
      - echo "Running tests..."
      - python3 -m pytest -vv --cov=hello test_hello.py
      # Optional: Define artifacts to upload to S3 (e.g., logs, reports)
      # post_build:
      #   commands:
      #     - echo "Post-build phase..."
