options:
  # Add these lines
  logging: CLOUD_LOGGING_ONLY # No GCS bucket required
  machineType: E2_HIGHCPU_8
steps:
  # Install dependencies with cache
  - name: python:3.11-slim
    id: install-deps
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install --user --upgrade pip
        pip install --user -r requirements-gcp.txt
    volumes:
      - name: pip-cache
        path: /root/.cache/pip
  # Run tests
  - name: python:3.11-slim
    id: run-tests
    entrypoint: bash
    args:
      - "-c"
      - |
        python -m pytest test_hello.py
